@extends(active_theme() . '.layouts.master')
@section('title')
    {{ settings()->name }}
@endsection
@section('content')
    @include(active_theme() . '.section.banner')
    @include(active_theme() . '.section.tracking')
    @include(active_theme() . '.section.partner')
    @include(active_theme() . '.section.service')
    @include(active_theme() . '.section.why_courier')
    @include(active_theme() . '.section.pricing')
    @include(active_theme() . '.section.process')
    @include(active_theme() . '.section.merchants')
    @include(active_theme() . '.section.gallery')
    @include(active_theme() . '.section.achievement')
    @include(active_theme() . '.section.testimonial')
    @include(active_theme() . '.section.newsletter')
    @include(active_theme() . '.section.blogs')
@endsection
@include(active_theme() . '.home-scripts')
